### ISSUE TITLE
Allow drupal contrib modules being updated to their recent minor versions

### ISSUE THREAD

**Issue by andriyun** [OS2Forms/os2forms_forloeb#58]
Due to support agreement with customer we should deliver all recent versions for contrib modules.

I see that some drupal contrib modules in os2forms/os2forms_forloeb package has been referenced to its strict versions.
For example: 
```
                "drupal/webform_views": "5.0.0-alpha7",
```
See https://github.com/OS2Forms/os2forms_forloeb/blob/master/composer.json#L53

It's blocking ability to update this module to its recent version.

## Proposed solution:

Added it by dynamic reference to it's recent minor version:
```
"drupal/webform_views": "^5.0.0-alpha",
```

**Comment by madsnorgaard** [comment]
I am ready to make this change too. In case of breaking changes on minor version we will have to find and solve errors as they happen. For now this does seem to be a way to reach a more dynamic setup. Let us make it a priority.

**Comment by lats1** [comment]
I agree. Also we should probably change this for all our dependencies.

**Comment by madsnorgaard** [comment]
I had closed by mistake and agree we should make this change.

**Comment by agger-magenta** [comment]
I'd like to say that we recently saw serious breakage because a minor version was _not_ strictly specified.

Specifically, when going from `dynamic_entity_reference` version `2.0.0-alpha14` to `2.0.0-alpha15`, Maestro orchestration crashed because of an SQL syntax error (see [this issue](https://www.drupal.org/project/dynamic_entity_reference/issues/3120952)).

This error was confusing and took quite a while to find. An alternative would be to depend on stable versions of packages, but that has other drawbacks. But if we don't specify the minor version, at least we should realize that upgrades can and will (at some point) introduce unexpected breaking changes.

**Comment by madsnorgaard** [comment]
Closing issue as solved per Drupal best practices.
